name: Deploy on Render
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Backend to Render
        run: curl "$RENDER_DEPLOY_HOOK_URL"
